version: '3.7'
services:
  dev:
      build:
        context: .
        dockerfile: Dockerfile.dev
        args:
          - timezone=Asia/Singapore
      env_file:
        - .env
      restart: always
      ports:
        - '3001:3000'
      volumes:
      - ./components:/test/components
      - ./composables:/test/composables
      - ./layouts:/test/layouts
      - ./pages:/test/pages
      - ./public:/test/public
      - ./server:/test/server
      - ./plugins:/test/plugins

      networks:
        - siwp2005-service-net
      command: "npm run dev"

networks:
  ui-service-net:
    name: siwp2005-service-net